name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

# ===========================================================================
jobs:
  # -------------------------------------------------------------------------
  # Code Quality Checks
  # -------------------------------------------------------------------------
  check:
    name: Test, Lint & Format
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout source
        uses: actions/checkout@v5

      - name: Install Rust toolchain
        run: |
          curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y --default-toolchain stable -c clippy -c rustfmt
          echo "$HOME/.cargo/bin" >> $GITHUB_PATH

      - name: Install system dependencies
        run: |
          sudo apt-get update
            sudo apt-get install -y \
              pkg-config \
              gettext \
              libgtk-4-dev \
              libadwaita-1-dev \
              libasound2-dev

      - name: Check formatting
        run: cargo fmt --check

      - name: Run Clippy
        run: cargo clippy -- -D warnings

      - name: Build translations
        run: |
          for f in po/*.po; do
            lang=$(basename "$f" .po)
            mkdir -p "target/locale/$lang/LC_MESSAGES"
            msgfmt "$f" -o "target/locale/$lang/LC_MESSAGES/khushu.mo"
          done

      - name: Run tests
        run: LANG=en_US.UTF-8 cargo test
